sudo: required

language: python

python:
    - "3.7"

services:
  - docker
stages:
  - name: docker-build
    if: branch = master
  - name: test

addons:
  apt:
    packages:
      - flawfinder
      - squashfs-tools
      - uuid-dev
      - libuuid1
      - libffi-dev
      - libssl-dev
      - libssl1.0.0
      - libarchive-dev
      - libgpgme11-dev
      - libseccomp-dev
      - liblzo2-dev
    update: true

jobs:
  include:
    - stage: docker-build
      script:
        - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then docker build -t quay.io/ucsc_cgl/cat:latest .; fi
        - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then docker login --username $QUAY_USERNAME --password $QUAY_PASSWORD quay.io; docker push quay.io/ucsc_cgl/cat:latest; fi
    - stage: test
      script:
        - set ex
        - pip install .
        # Have to screw with toil's settings to get the jobs to
        # actually run properly on such a small VM.
        - sed -i "s/maxDisk = self.physicalDisk/pass/g" $VIRTUAL_ENV/lib/*/site-packages/toil/batchSystems/singleMachine.py
        - sed -i "s/maxCores = self.numCores/maxCores = 8/g" $VIRTUAL_ENV/lib/*/site-packages/toil/batchSystems/singleMachine.py
        - sed -i "s/maxMemory = self.physicalMemory/pass/g" $VIRTUAL_ENV/lib/*/site-packages/toil/batchSystems/singleMachine.py
        - >
          luigi --module cat RunCat --hal=test_data/vertebrates.hal --target-genomes='("hg38", "galGal4")' --ref-genome=mm10
          --workers=2 --config=test_data/test.config --work-dir test_install --out-dir test_install --local-scheduler
          --augustus --augustus-cgp --augustus-pb --assembly-hub --logLevel DEBUG
    - stage: test
      script:
        - set ex
        - sudo add-apt-repository ppa:gophers/archive
        - sudo apt update
        - sudo apt install golang-1.11-go
        - >
          export VERSION=3.5.2 && # adjust this as necessary
          wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz &&
          tar -xzf singularity-${VERSION}.tar.gz &&
          cd singularity && ./mconfig && make -C builddir && sudo make -C builddir install
        - pip install .
        # Have to screw with toil's settings to get the jobs to
        # actually run properly on such a small VM.
        - sed -i "s/maxDisk = self.physicalDisk/pass/g" $VIRTUAL_ENV/lib/*/site-packages/toil/batchSystems/singleMachine.py
        - sed -i "s/maxCores = self.numCores/maxCores = 8/g" $VIRTUAL_ENV/lib/*/site-packages/toil/batchSystems/singleMachine.py
        - sed -i "s/maxMemory = self.physicalMemory/pass/g" $VIRTUAL_ENV/lib/*/site-packages/toil/batchSystems/singleMachine.py
        - >
          luigi --module cat RunCat --hal=test_data/vertebrates.hal --target-genomes='("hg38", "galGal4")' --ref-genome=mm10
          --workers=2 --config=test_data/test.config --work-dir test_install --out-dir test_install --local-scheduler
          --augustus --augustus-cgp --augustus-pb --assembly-hub --binary-mode singularity